// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SGCP_POO.Models;

#nullable disable

namespace SGCP_POO.Migrations
{
    [DbContext(typeof(SGCPContext))]
    [Migration("20260225045356_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SGCP_POO.Models.Estudiante", b =>
                {
                    b.Property<int>("IdEstudiante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_estudiante");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEstudiante"));

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("contraseña");

                    b.Property<string>("CorreoInstitucional")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correo_institucional");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdEstudiante")
                        .HasName("PK__Estudian__E0B2763CD343FFC2");

                    b.HasIndex(new[] { "CorreoInstitucional" }, "UQ__Estudian__107A1DDABF1DAFB4")
                        .IsUnique();

                    b.ToTable("Estudiante", (string)null);
                });

            modelBuilder.Entity("SGCP_POO.Models.Informacion", b =>
                {
                    b.Property<int>("IdInformacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_informacion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdInformacion"));

                    b.Property<string>("CorreoPersonal")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correo_personal");

                    b.Property<string>("Deficiencias")
                        .HasColumnType("text")
                        .HasColumnName("deficiencias");

                    b.Property<int?>("Edad")
                        .HasColumnType("integer")
                        .HasColumnName("edad");

                    b.Property<string>("Habilidades")
                        .HasColumnType("text")
                        .HasColumnName("habilidades");

                    b.Property<int?>("IdEstudiante")
                        .HasColumnType("integer")
                        .HasColumnName("id_estudiante");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.Property<int?>("TiempoDedicacion")
                        .HasColumnType("integer")
                        .HasColumnName("tiempo_dedicacion");

                    b.HasKey("IdInformacion")
                        .HasName("PK__Informac__5E0F3B9E69DBAC86");

                    b.HasIndex("IdEstudiante");

                    b.ToTable("Informacion", (string)null);
                });

            modelBuilder.Entity("SGCP_POO.Models.Recurso", b =>
                {
                    b.Property<int>("IdRecurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_recurso");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRecurso"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(700)
                        .HasColumnType("character varying(700)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Dificultad")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("dificultad");

                    b.Property<string>("Enlace")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("enlace");

                    b.Property<string>("Formato")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("formato");

                    b.Property<int>("IdEstudiante")
                        .HasColumnType("integer")
                        .HasColumnName("id_estudiante");

                    b.Property<string>("PalabrasClave")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("palabras_clave");

                    b.Property<string>("Tema")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("tema");

                    b.Property<string>("Titulo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("titulo");

                    b.HasKey("IdRecurso");

                    b.HasIndex("IdEstudiante");

                    b.ToTable("Recurso", (string)null);
                });

            modelBuilder.Entity("SGCP_POO.Models.TarjetaConocimiento", b =>
                {
                    b.Property<int>("IdTarjeta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_tarjeta");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTarjeta"));

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IdEstudiante")
                        .HasColumnType("integer")
                        .HasColumnName("id_estudiante");

                    b.Property<string>("NombreTarjeta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_tarjeta");

                    b.HasKey("IdTarjeta");

                    b.HasIndex("IdEstudiante");

                    b.ToTable("TarjetaConocimiento", (string)null);
                });

            modelBuilder.Entity("SGCP_POO.Models.TarjetaRecurso", b =>
                {
                    b.Property<int>("IdTarjetaRecurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_tarjeta_recurso");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTarjetaRecurso"));

                    b.Property<int?>("Calificacion")
                        .HasColumnType("integer")
                        .HasColumnName("calificacion");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IdRecurso")
                        .HasColumnType("integer")
                        .HasColumnName("id_recurso");

                    b.Property<int>("IdTarjeta")
                        .HasColumnType("integer")
                        .HasColumnName("id_tarjeta");

                    b.Property<string>("Retroalimentacion")
                        .HasColumnType("text")
                        .HasColumnName("retroalimentacion");

                    b.HasKey("IdTarjetaRecurso");

                    b.HasIndex("IdRecurso");

                    b.HasIndex("IdTarjeta");

                    b.ToTable("TarjetaRecurso", (string)null);
                });

            modelBuilder.Entity("SGCP_POO.Models.Informacion", b =>
                {
                    b.HasOne("SGCP_POO.Models.Estudiante", "IdEstudianteNavigation")
                        .WithMany("Informacions")
                        .HasForeignKey("IdEstudiante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Informaci__id_es__3D5E1FD2");

                    b.Navigation("IdEstudianteNavigation");
                });

            modelBuilder.Entity("SGCP_POO.Models.Recurso", b =>
                {
                    b.HasOne("SGCP_POO.Models.Estudiante", "IdEstudianteNavigation")
                        .WithMany("Recursos")
                        .HasForeignKey("IdEstudiante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdEstudianteNavigation");
                });

            modelBuilder.Entity("SGCP_POO.Models.TarjetaConocimiento", b =>
                {
                    b.HasOne("SGCP_POO.Models.Estudiante", "Estudiante")
                        .WithMany("Tarjetas")
                        .HasForeignKey("IdEstudiante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("SGCP_POO.Models.TarjetaRecurso", b =>
                {
                    b.HasOne("SGCP_POO.Models.Recurso", "Recurso")
                        .WithMany("TarjetaRecursos")
                        .HasForeignKey("IdRecurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGCP_POO.Models.TarjetaConocimiento", "Tarjeta")
                        .WithMany("TarjetasRecursos")
                        .HasForeignKey("IdTarjeta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recurso");

                    b.Navigation("Tarjeta");
                });

            modelBuilder.Entity("SGCP_POO.Models.Estudiante", b =>
                {
                    b.Navigation("Informacions");

                    b.Navigation("Recursos");

                    b.Navigation("Tarjetas");
                });

            modelBuilder.Entity("SGCP_POO.Models.Recurso", b =>
                {
                    b.Navigation("TarjetaRecursos");
                });

            modelBuilder.Entity("SGCP_POO.Models.TarjetaConocimiento", b =>
                {
                    b.Navigation("TarjetasRecursos");
                });
#pragma warning restore 612, 618
        }
    }
}
